// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Product struct {
	ID        int32   `json:"id"`
	Name      string  `json:"name"`
	SellPrice float64 `json:"sell_price"`
	CreatedAt string  `json:"created_at"`
}

type Purchase struct {
	ID        int32   `json:"id"`
	ProductID int32   `json:"product_id"`
	Qty       float64 `json:"qty"`
	CostPrice float64 `json:"cost_price"`
	TotalCost float64 `json:"total_cost"`
	CreatedBy int32   `json:"created_by"`
	CreatedAt string  `json:"created_at"`
}

type Sale struct {
	ID           int32   `json:"id"`
	ProductID    int32   `json:"product_id"`
	Qty          float64 `json:"qty"`
	SellPrice    float64 `json:"sell_price"`
	TotalRevenue float64 `json:"total_revenue"`
	CreatedBy    int32   `json:"created_by"`
	CreatedAt    string  `json:"created_at"`
}

type StockLevel struct {
	ProductID int32   `json:"product_id"`
	Qty       float64 `json:"qty"`
	CostPrice float64 `json:"cost_price"`
	UpdatedAt string  `json:"updated_at"`
}

type User struct {
	ID        int32  `json:"id"`
	TgID      int64  `json:"tg_id"`
	FullName  string `json:"full_name"`
	Role      string `json:"role"`
	CreatedAt string `json:"created_at"`
}
