// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: purchases.sql

package db

import (
	"context"
)

const addPurchase = `-- name: AddPurchase :one
INSERT INTO purchases (product_id, qty, cost_price, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, product_id, qty, cost_price, total_cost, created_by, created_at
`

type AddPurchaseParams struct {
	ProductID int32   `json:"product_id"`
	Qty       float64 `json:"qty"`
	CostPrice float64 `json:"cost_price"`
	CreatedBy int32   `json:"created_by"`
}

func (q *Queries) AddPurchase(ctx context.Context, arg AddPurchaseParams) (Purchase, error) {
	row := q.db.QueryRow(ctx, addPurchase,
		arg.ProductID,
		arg.Qty,
		arg.CostPrice,
		arg.CreatedBy,
	)
	var i Purchase
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Qty,
		&i.CostPrice,
		&i.TotalCost,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
