// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AddPurchase(ctx context.Context, arg AddPurchaseParams) (Purchase, error)
	AddSale(ctx context.Context, arg AddSaleParams) (Sale, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	GetProductByName(ctx context.Context, name string) (Product, error)
	ListProducts(ctx context.Context) ([]ListProductsRow, error)
	ReduceStock(ctx context.Context, arg ReduceStockParams) error
	UpsertStock(ctx context.Context, arg UpsertStockParams) error
}

var _ Querier = (*Queries)(nil)
